version: "3.8"

services:
  postgres:
    image: ankane/pgvector
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # xinference:
  #   image: xprobe/xinference:latest
  #   ports:
  #     - "9997:9997"
  #   volumes:
  #     # If models are downloaded from modelscope, replace <huggingface_cache_dir> with
  #     # your modelscope cache path, default is <home_path>/.cache/modelscope
  #     - xinference-data:/root/.cache/modelscope
  #   environment:
  #     # add envs here. Here's an example, if you want to download model from modelscope
  #     - XINFERENCE_MODEL_SRC=modelscope
  #   command: xinference-local --host 0.0.0.0 --port 9997
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]
  #             driver: nvidia
  #             count: all

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_KEY}
    volumes:
      - minio-data:/data
      - minio-config:/root/.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

volumes:
  postgres-data:
  xinference-data:
  minio-data:
  minio-config:
