# fly.toml file generated for quiet-sea-3893 on 2022-12-04T11:47:53+13:00

app = "quiet-sea-3893"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  DB_URL = "/data/app.db"

[experimental]
  auto_rollback = true
  enable_consul = true

# [[mounts]]
#   destination = "/mnt/data"
#   processes = ["web"]
#   source = "data"

[processes]
web = "litefs -config /etc/litefs-web.yml"
worker = "litefs -config /etc/litefs-worker.yml"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"

[statics]
  guest_path = "/home/user/app/app/static"
  processes = ["web"]
  url_prefix = "/static"
