# fly.toml app configuration file generated for leafletv2 on 2024-05-22T09:56:00-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'leafletv2'
primary_region = 'ewr'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['server']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  server = "inv server-prod"
  worker = "inv worker-prod"

[[statics]]
  url_prefix = "/static"
  processes = ["server"]

[deploy]
  release_command = "inv db-up"
