[tool.poetry]
name = "leaflet"
version = "0.1.0"
description = ""
authors = ["Craig Mulligan <git@hobochild.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
itsdangerous = "^2.0.1"
gunicorn = "^20.1.0"
celery = "^5.2.7"
SQLAlchemy = "^1.4.42"
Flask = "^2.2.2"
recipe-scrapers = "^14.23.0"
pint = "^0.20.1"
ingredient-parser-nlp = "^0.1.0a3"
python-dotenv = "^0.21.0"
psycopg2-binary = "^2.9.5"
yoyo-migrations = "^8.1.0"

[tool.poetry.dev-dependencies]
freezegun = "^1.2.2"
black = "^22.10.0"
watchdog = { extras = ["watchmedo"], version = "^2.1.6" }
pytest-cov = "^3.0.0"
pyright = "^1.1.247"
types-freezegun = "^1.1.4"
pytest = "^6.2.5"
pytest-testmon = "^1.3.6"
pytest-watch = "^4.2.0"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools-scm!=6.1.1,!=6.3.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
exclude = "venv"

[[tool.mypy.overrides]]
module = "celery,freezegun"
ignore_missing_imports = true
