"""user prompt

Revision ID: 6e0e48de2429
Revises: cb0dd456e4cc
Create Date: 2024-05-06 17:09:10.118818

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e0e48de2429"
down_revision: Union[str, None] = "cb0dd456e4cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_account", sa.Column("prompt", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "prompt")
    # ### end Alembic commands ###
