faqs = [
    (
        "What is this?",
        'Leaflet is a tool to help you eat more plant based meals week on week. You give it a prompt to customize it to your needs and it will then send you a weekly "leaflet" of 3 randomly generated plant-based recipes.',
    ),
    (
        "Why did you make this?",
        "I grew up in South Africa, a country like many others, whose cuisine is dominated by meat. As I was transitioning to a plant based diet, I didn't have any vegetarian recipes to fallback on. I found learning a totally new set of \"go-to\" recipes difficult. But it's also useful if you'd just like to learn new recipes.",
    ),
    (
        "Where do the recipes come from?",
        "Everything, the recipes, the images and even the recipe search index is generated by generative AI (aka ChatGPT).",
    ),
]
