name: CI tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: docker-compose up -d
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.6'
    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: '1.2.2'
    - run: poetry install
    - run: poetry run flask dev mypy
    - run: poetry run flask dev test
