name: CI tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: abatilo/actions-poetry@v2.0.0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.8'
    - run: poetry install
    # - run: poetry run flask dev fmt -- --check
    - run: poetry run flask dev mypy
    - run: poetry run flask dev test
